localisation:
    ros__parameters:
        update_frequency: 50.0

local_planner:
    ros__parameters:
        update_frequency: 10.0
        car_width: 2.0
        centreofgravity_to_frontaxle: 1.483
        frame_id: "base_link"

global_planner:
    ros__parameters:
        update_frequency: 2.0
        waypoints_ahead: 3
        waypoints_behind: 2
        passed_threshold: 0.25
        centreofgravity_to_frontaxle: 1.483

path_tracker:
    ros__parameters:
        update_frequency: 50.0
        control_gain: 1.0
        softening_gain: 1.0
        yawrate_gain: 1.0
        steering_limits: 0.95
        centreofgravity_to_frontaxle: 1.483